# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Dec  8 00:27:05 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1029, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1021, 541))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.teLog = QtGui.QPlainTextEdit(self.widget)
        self.teLog.setEnabled(True)
        self.teLog.setObjectName(_fromUtf8("teLog"))
        self.horizontalLayout.addWidget(self.teLog)
        self.teCars = QtGui.QPlainTextEdit(self.widget)
        self.teCars.setEnabled(True)
        self.teCars.setObjectName(_fromUtf8("teCars"))
        self.horizontalLayout.addWidget(self.teCars)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblCarsNum = QtGui.QLabel(self.widget)
        self.lblCarsNum.setObjectName(_fromUtf8("lblCarsNum"))
        self.verticalLayout.addWidget(self.lblCarsNum)
        self.leCarsNum = QtGui.QLineEdit(self.widget)
        self.leCarsNum.setObjectName(_fromUtf8("leCarsNum"))
        self.verticalLayout.addWidget(self.leCarsNum)
        self.lblGenExpVal = QtGui.QLabel(self.widget)
        self.lblGenExpVal.setObjectName(_fromUtf8("lblGenExpVal"))
        self.verticalLayout.addWidget(self.lblGenExpVal)
        self.leGenExpVal = QtGui.QLineEdit(self.widget)
        self.leGenExpVal.setObjectName(_fromUtf8("leGenExpVal"))
        self.verticalLayout.addWidget(self.leGenExpVal)
        self.lblProcExpVal = QtGui.QLabel(self.widget)
        self.lblProcExpVal.setObjectName(_fromUtf8("lblProcExpVal"))
        self.verticalLayout.addWidget(self.lblProcExpVal)
        self.leProcExpVal = QtGui.QLineEdit(self.widget)
        self.leProcExpVal.setObjectName(_fromUtf8("leProcExpVal"))
        self.verticalLayout.addWidget(self.leProcExpVal)
        self.lblProcDiap = QtGui.QLabel(self.widget)
        self.lblProcDiap.setObjectName(_fromUtf8("lblProcDiap"))
        self.verticalLayout.addWidget(self.lblProcDiap)
        self.leProcDiap = QtGui.QLineEdit(self.widget)
        self.leProcDiap.setObjectName(_fromUtf8("leProcDiap"))
        self.verticalLayout.addWidget(self.leProcDiap)
        self.lblRowsNum = QtGui.QLabel(self.widget)
        self.lblRowsNum.setObjectName(_fromUtf8("lblRowsNum"))
        self.verticalLayout.addWidget(self.lblRowsNum)
        self.leRowsNum = QtGui.QLineEdit(self.widget)
        self.leRowsNum.setObjectName(_fromUtf8("leRowsNum"))
        self.verticalLayout.addWidget(self.leRowsNum)
        self.lblStationsInRowNum = QtGui.QLabel(self.widget)
        self.lblStationsInRowNum.setObjectName(_fromUtf8("lblStationsInRowNum"))
        self.verticalLayout.addWidget(self.lblStationsInRowNum)
        self.leStationsInRowNum = QtGui.QLineEdit(self.widget)
        self.leStationsInRowNum.setObjectName(_fromUtf8("leStationsInRowNum"))
        self.verticalLayout.addWidget(self.leStationsInRowNum)
        self.pbEvent = QtGui.QPushButton(self.widget)
        self.pbEvent.setObjectName(_fromUtf8("pbEvent"))
        self.verticalLayout.addWidget(self.pbEvent)
        self.lblAvgTimeInQueue = QtGui.QLabel(self.widget)
        self.lblAvgTimeInQueue.setText(_fromUtf8(""))
        self.lblAvgTimeInQueue.setObjectName(_fromUtf8("lblAvgTimeInQueue"))
        self.verticalLayout.addWidget(self.lblAvgTimeInQueue)
        self.lblAvgTimeToLeave = QtGui.QLabel(self.widget)
        self.lblAvgTimeToLeave.setText(_fromUtf8(""))
        self.lblAvgTimeToLeave.setObjectName(_fromUtf8("lblAvgTimeToLeave"))
        self.verticalLayout.addWidget(self.lblAvgTimeToLeave)
        self.lblFreedTime = QtGui.QLabel(self.widget)
        self.lblFreedTime.setText(_fromUtf8(""))
        self.lblFreedTime.setObjectName(_fromUtf8("lblFreedTime"))
        self.verticalLayout.addWidget(self.lblFreedTime)
        self.lblWastedTime = QtGui.QLabel(self.widget)
        self.lblWastedTime.setText(_fromUtf8(""))
        self.lblWastedTime.setObjectName(_fromUtf8("lblWastedTime"))
        self.verticalLayout.addWidget(self.lblWastedTime)
        self.lblModelingTime = QtGui.QLabel(self.widget)
        self.lblModelingTime.setText(_fromUtf8(""))
        self.lblModelingTime.setObjectName(_fromUtf8("lblModelingTime"))
        self.verticalLayout.addWidget(self.lblModelingTime)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Моделирование заправки", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCarsNum.setText(QtGui.QApplication.translate("MainWindow", "Число машин", None, QtGui.QApplication.UnicodeUTF8))
        self.leCarsNum.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGenExpVal.setText(QtGui.QApplication.translate("MainWindow", "Матожидание генератора", None, QtGui.QApplication.UnicodeUTF8))
        self.leGenExpVal.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProcExpVal.setText(QtGui.QApplication.translate("MainWindow", "Матожидание заправки", None, QtGui.QApplication.UnicodeUTF8))
        self.leProcExpVal.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProcDiap.setText(QtGui.QApplication.translate("MainWindow", "Полуинтервал заправки", None, QtGui.QApplication.UnicodeUTF8))
        self.leProcDiap.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRowsNum.setText(QtGui.QApplication.translate("MainWindow", "Число рядов колонок", None, QtGui.QApplication.UnicodeUTF8))
        self.leRowsNum.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStationsInRowNum.setText(QtGui.QApplication.translate("MainWindow", "Число колонок в ряду", None, QtGui.QApplication.UnicodeUTF8))
        self.leStationsInRowNum.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEvent.setText(QtGui.QApplication.translate("MainWindow", "Событийная протяжка", None, QtGui.QApplication.UnicodeUTF8))

